### ISSUE TITLE
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

### ISSUE THREAD

**Issue by guru65476** [SamPandey001/Zero-Two-MD#13]
Resolving download.imagemagick.org (download.imagemagick.org)... 50.251.58.13
Connecting to download.imagemagick.org (download.imagemagick.org)|50.251.58.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-30 00:28:10 ERROR 404: Not Found.
-----> Extracting ImageMagick from /tmp/build_e7bbe91a/ImageMagick-7.0.5-10.tar.xz
       Error: Unable to download ImageMagick
       app.json
       assets

**Comment by SamPandey001** [comment]
Are you still facing this issue?
